name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - numpy=1.19.1
  - pip=20.3.3
  - scikit-learn=0.24.1
  - pip:
      - protobuf==3.19.1
      - wandb==0.10.21